export const allRoutes = {
    home: '/',
    faq: '/faq',
    cart: '/cart',
    blog: '/blog',
    press: '/press',
    about: '/about-us',
    signUp: '/sign-up',
    login: '/login',
    contactUs: '/contact-us',
    checkout: '/checkout',
    thankYou: '/thank-you',
    refundPolicy: '/refund-policy',
    resetPassword: '/reset-password',
    address: '/cart/address',
    payment: '/cart/payment',
    shop: '/shop',
    paymentFailed: '/payment-failed',
    underMaintenance: '/under-maintenance',
  }
  